In [1]:
import numpy as np

In [10]:
x = np.random.randint(1,21,10)
print(x)
x1 = np.arange(2,12)
print(x1)
print(x + x1)
#Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 1 до 20, затем создайте массив состоящий из 10 элементов, начиная с 2. Выведите значения этих массивов, а также их сумму, при помощи функции print()

[ 3 10  5  5 14  7  1 15 15  1]
[ 2  3  4  5  6  7  8  9 10 11]
[ 5 13  9 10 20 14  9 24 25 12]


In [12]:
x = np.random.randint(0,10, 7)
print(x)
print(x * 3)
#Создайте массив , состоящий из 7 случайных целых чисел из диапазона от 0 до 9, затем создайте новый массив состоящий из 7 элементов первого массива, увеличенных в 3 раза. Выведите значения этих массивов при помощи функции print()

[6 8 7 5 2 0 8]
[18 24 21 15  6  0 24]


In [25]:
np.sqrt(np.arange(7, 7+20))


array([2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
       4.12310563, 4.24264069, 4.35889894, 4.47213595, 4.58257569,
       4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951])