In [2]:
import numpy as np

In [6]:
x = np.random.randint(1,21, 10)
print(x)
print(x[1:6])
#Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 1 до 20, затем создайте массив состоящий из 5 элементов, начиная со 2 по порядку. Выведите значения обоих массивов при помощи функции print()

[ 8 12  7 11  8 14  4  3  5  4]
[12  7 11  8 14]


In [7]:
x = np.random.randint(0,21,10)
print(x)
print(x[2:])
#Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 0 до 20, затем создайте массив состоящий из элементов, начиная с третьего по порядку до последнего. Выведите значения обоих массивов при помощи функции print()

[12 18  7 19 18 14 15  6 15  1]
[ 7 19 18 14 15  6 15  1]


In [17]:
x = np.random.randint(3,12, 12).reshape(3,4)
print(x)
print(" ")
print(x[1:3,1:3])
#Создайте двумерный массив , состоящий из случайных целых чисел из диапазона от 3 до 11, в котором 4 строки и 3 столбца. Затем создайте массив состоящий из элементов , второй и третьей строки и первого и второго столбца по порядку. Выведите значения обоих массивов при помощи функции print()

[[11  9  6  8]
 [ 7 11  5 10]
 [11  4  4  8]]
 
[[11  5]
 [ 4  4]]


In [25]:
x = np.random.randint(0,9, 6*4).reshape(4,6)
print(x)
print(x[x > 3])
#Создайте двумерный массив , состоящий из случайных целых чисел из диапазона от 0 до 9, в котором 4 строки и 6 столбцов. Затем создайте массив состоящий из элементов , которые больше числа 3. Выведите значения обоих массивов при помощи функции print()

[[5 3 4 3 4 6]
 [3 0 0 7 2 1]
 [3 4 3 5 4 6]
 [5 8 2 4 5 7]]
[5 4 4 6 7 4 5 4 6 5 8 4 5 7]
