In [72]:
import numpy as np
np.array([0,1,2,3,4,5,6,7,8,9]) 
# Создайте массив из списка, , состоящего из чисел от 0 до 9, при помощи функции array() из модуля numpy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.arange(0,20, 2)
# Создайте массив , состоящий из нечётных чисел от 1 до 19, при помощи функции arange() из модуля numpy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [74]:
np.zeros(20)
# Создайте массив , состоящий из двадцати нулей

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [89]:
x = np.ones(20)
x.reshape(4, 5)
# Создайте двумерный массив , состоящий из двадцати единиц, в котором 5 строк и 4 столбца

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
np.linspace(3,7,5)
# Создайте массив , состоящий из пяти равномерно распределённых чисел от 3 до 7

array([3., 4., 5., 6., 7.])

In [101]:
np.linspace(3,7,9).reshape(3,3)
# Создайте двумерный массив , состоящий из 9 равномерно распределённых чисел от 3 до 7

array([[3. , 3.5, 4. ],
       [4.5, 5. , 5.5],
       [6. , 6.5, 7. ]])

In [131]:
x = np.random.randint(1,101, 10)
print(x)
max_number = x.max()
print(max_number)
#Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 1 до 100, присвойте его максимальное значение переменной max_number и выведите значение этой переменной при помощи функции print()

[50 36 10 82 10 76 37 93 75 42]
93
